### ISSUE TITLE
Publish new version?

### ISSUE THREAD

**Issue by szehetner** [AdaptiveConsulting/Aeron.NET#102]
Unless there are other changes planned in the short term, could you publish NuGet packages for the current version (i.e. with https://github.com/AdaptiveConsulting/Aeron.NET/pull/100 and https://github.com/AdaptiveConsulting/Aeron.NET/pull/101)? 

Thanks!

**Comment by JPWatson** [comment]
Sure, thing.

**Comment by szehetner** [comment]
Just pinging, any news on new package versions?

**Comment by JPWatson** [comment]
Apologies for the delay on this. I'm waiting for the v1.33.0 of the Java version as there are some big improvements to cluster APIs.

**Comment by hich9n** [comment]
hi all, we are considering using this great library, but it has been a long time since last commit! do you still actively maintain this project?

**Comment by JPWatson** [comment]
Yep, still actively maintaining (whenever I get some spare time). I'm hoping to do changes to bring in line with the latest version of Aeron soon.
