### ISSUE TITLE
Remove Environment.Exit(-1) as default behaviour when driver connection is lost?

### ISSUE THREAD

**Issue by szehetner** [AdaptiveConsulting/Aeron.NET#104]
I just stumbled upon this line:

https://github.com/AdaptiveConsulting/Aeron.NET/blob/0955ab0bc32bb1cb673ffdf612d1820cd9e77b3e/src/Adaptive.Aeron/Aeron.cs#L483

The default error handler calls Environment.Exit(-1) when the driver connection is lost. It took me a while to track this down as we are running in a Windows Service which doesn't have Console.Error by default. So the preceding messages are lost, all you get is a process that just exits intermittently without any indication as to why. While obviously one should anyway track Console.Error  output and always provide a custom error handler, I think this may come as a surprise to others as well.

I would say it is rather unexpected that a library terminates the hosting process, especially as default behaviour. Shouldn't this be removed, i.e. the Console.Error output should be enough in a default error handler?

**Comment by JPWatson** [comment]
It's a fair point. This is the behaviour in all of the Aeron client libraries so I'm hesitant to diverge. Also, changing this now would be a breaking change in behaviour.

You are free to override the error handler to handle errors appropriately for the context in which they are running.
