### ISSUE TITLE
Codec Generation

### ISSUE THREAD

**Issue by adetonak** [AdaptiveConsulting/Aeron.NET#113]
- How were the codecs (e.g. NewLeaderEventDecoder) in this project generated, please?
- Crucially, the generated code of the codecs in this project look different to what's generated by latest SbeTool
- The `Adaptive.Agrona.IFragmentHandler.OnFragment()` accepts a `Adaptive.Agrona.IDirectBuffer` parameter
- However, the SbeTool generated codec operate on `Org.SbeTool.Sbe.Dll.DirectBuffer` which does not implement `Adaptive.Agrona.IDirectBuffer`
- How can I translate between these two buffers (i.e. `Org.SbeTool.Sbe.Dll.DirectBuffer` <-> `Adaptive.Agrona.IDirectBuffer`) please ?

**Comment by JPWatson** [comment]
It uses this code generator https://github.com/JPWatson/sbe-generators which mirrors the java generator more closely.

Jars are currently bundled into the repository and you can see the script that generates them here:
https://github.com/AdaptiveConsulting/Aeron.NET/blob/master/scripts/generate-archive-codecs.bat

Currently the buffer implementations between SBE and Aeron.NET do not line up. We've talked about aligning them but we've haven't had time to do that yet. 

In the meantime, there are a couple of gists that might be helpful:
https://gist.github.com/JPWatson/5fc62671b2eeffaea01683b7588705ef
https://gist.github.com/JPWatson/0d8ebceae8283af3e15411562db8742b

**Comment by adetonak** [comment]
Very helpful, thanks !!!
