### ISSUE TITLE
Structs vs Classes

### ISSUE THREAD

**Issue by buybackoff** [AdaptiveConsulting/Aeron.NET#31]
I wonder why you do not use structs vs classes where it makes code more idiomatic to .NET and helps to avoid allocations? I see that you have classes vs structs on some hot paths. E.g. `BufferClaim` is a class. `UnsafeBuffer` is also a class, however both are very close to `ArraySegment<byte>` by usage semantics. There is a mantra that short-lived objects are very cheap to allocate and collect in .NET, but the costs are not zero.

Or maybe your intent is to reuse objects when possible and use `Wrap()` methods, as commented [here](https://github.com/AdaptiveConsulting/Aeron/blob/1f47dd69833a44d652b0f5e1adeb94d8df9d389f/src/Adaptive.Aeron/Publication.cs#L268)? E.g. you mutate `BufferClaim` that is passed to a method and then use the same instance in a loop. But what if we want to claim space for a result of some work, and then complete this work asynchronously using a task? We could pass a struct easily by value between threads in such a scenario, but cannot reuse a class and have to allocate. The same is true for `UnsafeBuffers` - if they are structs, we could create as many instances as convenient for free, and still reuse a single instance if we want to do so.

Additionally, there is `call` vs `callvirt` and interface method call _minor_ issue. In JVM, everything is an object and probably method calls are optimized more than in CLR. However, inside tight loops I have noticed that interface method calls are noticeably slower than direct method calls. In the `Direct/UnsafeBuffer` case, all we do is writing to/reading from a pointer in unsafe code, e.g. `PutLog`, etc. Usually this is a very simple method with a couple of instructions, and then method call overhead becomes visible. That could matter in IPC case for Aeron, less so for networking. In your implementation, there is only one implementation of different buffer interfaces, so, at this stage, class hierarchy adds only overheads. Also, `UnsafeBuffer` currently works both with `byte[]` and `IntPtr`, and a single concrete implementation as a struct will be the fastest. (I separated them in my implementation initially, but will soon merge back to avoid using interfaces altogether).

I have just done a [trivial test](https://github.com/Spreads/Spreads/commit/205ad057f6a4ba231d61b6554e436828a5741df8) to show this. At first, I tested integer increment (i++), and struct method call was completely eliminated/inlined. In a [more realistic scenario](https://github.com/Spreads/Spreads/commit/94e844bfc17a3a008b1066973bfaada058aa619f), structs do not differ much from sealed classes, but interface overheads are clearly visible.

Struct vs classes was the only change I did while porting LogBuffers. My implementation of `DirectBuffer` was originally based on a `DirectBuffer` C# port in SBE by Adaptive (which, in turn, was the same port from Argona), but I then reworked it for the reasons described above.

**Comment by buybackoff** [comment]
I will look closer to the Aeron tests. Currently Aeron.NET's UnsafeBuffer methods are already sealed and are not used in any test directly (there is a recent commit where virtual was removed). My first thought was that we just need to mock IntPtr via Marshal.Allochglobal, because the buffer is just a view into some memory region, the methods behavior should be the same in tests.

**Comment by mjpt777** [comment]
Java's lack of of structs (Value Types) should not hold back the .NET client from having a better implementation that is more idiomatic to C#.

**Comment by buybackoff** [comment]
Interestingly, simply making UnsafeBuffer a struct kills performance to 10 Mops. I have read somewhere that JIT does not inline struct methods as aggressively as ones from classes. Or buffers-as-structs are passed by value too often in Aeron so that a simple change from a class to a struct is not enough. Before this exercise I had misconception that structs are universally superior due to GC.
