### ISSUE TITLE
Call vs Callvirt

### ISSUE THREAD

**Issue by JPWatson** [AdaptiveConsulting/Aeron.NET#33]
Copied from #31 
There is call vs callvirt and interface method call minor issue. In JVM, everything is an object and probably method calls are optimized more than in CLR. However, inside tight loops I have noticed that interface method calls are noticeably slower than direct method calls. In the Direct/UnsafeBuffer case, all we do is writing to/reading from a pointer in unsafe code, e.g. PutLog, etc. Usually this is a very simple method with a couple of instructions, and then method call overhead becomes visible. That could matter in IPC case for Aeron, less so for networking. In your implementation, there is only one implementation of different buffer interfaces, so, at this stage, class hierarchy adds only overheads. Also, UnsafeBuffer currently works both with byte[] and IntPtr, and a single concrete implementation as a struct will be the fastest. (I separated them in my implementation initially, but will soon merge back to avoid using interfaces altogether).

**Comment by buybackoff** [comment]
I get 21+ Mops in this branch.
I replaced all interfaces on top of the last change in #29. Without that change simply replacing interfaces with UnsafeBuffer only yields c.15 Mops.

**Comment by buybackoff** [comment]
In .NET, other than interface method call overheads, interface methods calls cannot be inlined by JIT compiler, that explains almost all the difference as @mjpt777 mentioned in #29.

**Comment by JPWatson** [comment]
fixed in #45
