### ISSUE TITLE
Add MediaDriver .jar and .bat as NuGet package content

### ISSUE THREAD

**Issue by buybackoff** [AdaptiveConsulting/Aeron.NET#35]
It is quite easy to pack a custom file as a resource into a dll and then extract it into a temp or fixed folder on application startup or some type initialization. Java is installed on most machines these days. Packed media driver will make .NET development experience seamless. It is not a big deal to start it manually from source, but NuGet experience and distribution of updates would be simpler.

**Comment by odeheurles** [comment]
Would be better to keep the jar outside of our repo, Martin is releasing new versions quite often and git is not the best place to store binaries.

The nuget + .bat file would be fine in development.
For prod deployment you'd probably want to run the media driver as a windows service, they are quite a few java wrappers out there to run a .jar file as a windows service.

**Comment by JPWatson** [comment]
@buybackoff I've uploaded a package:

`PM> Install-Package Aeron.Driver`
