### ISSUE TITLE
.NET Core support

### ISSUE THREAD

**Issue by buybackoff** [AdaptiveConsulting/Aeron.NET#48]
Are you going to support .NET Core soon? It should be quite trivial unless I missed something. It is mostly `#if`s for different APIs, e.g. `MemoryBarrier` was moved from `Thread` to `Interlocked`, deprecated `MemoryMappedFileSecurity`, etc.

**Comment by JPWatson** [comment]
seems like a good plan. I'm not going to have time to do it for a while though. Happy to review PRs though :)

**Comment by danielcrenna** [comment]
Adding, and this might be a naive question, but are they any plans to port the driver itself?

**Comment by JPWatson** [comment]
No plans at the moment but there is currently a C++ driver in the works which would remove the dependency on the JVM.

**Comment by danielcrenna** [comment]
Thanks, yes even a `libaeron` would suffice. I'll keep tabs. Cheers!

**Comment by ogreenz** [comment]
I would love .NET core support as well. has anyone started the porting?

**Comment by JPWatson** [comment]
Not that I'm aware of.

**Comment by JPWatson** [comment]
Had a go at porting to .NET Standard 1.3, most of the stuff is there but some important stuff if missing like Thread.Yield(). Think it's best to wait until .NET Standard 2.0 is released.
https://github.com/dotnet/standard/issues/34

**Comment by UncleFirefox** [comment]
#69 

Doing a first attempt on the tooling port, some stuff might be unstable if somebody wants to check

**Comment by JPWatson** [comment]
I've just uploaded a pre-release version of Aeron.NET 
https://www.nuget.org/packages/Aeron.Client/1.4.0-standard

It supports .net standard 2.0.

Will transition to stable with the next batch of functionality.

Thanks to @UncleFirefox

**Comment by AceHack** [comment]
Any updates on .NET core sable and C++ driver?

**Comment by JPWatson** [comment]
v1.4 is available with core support here https://www.nuget.org/packages/Aeron.Client/1.4.0-standard.
C++ driver on Windows is coming though I've got no timeline.
