### ISSUE TITLE
HeaderWriter Memory Barrier

### ISSUE THREAD

**Issue by JPWatson** [AdaptiveConsulting/Aeron.NET#49]
Having removed a memory barrier here, there was quite a larger performance:
https://github.com/AdaptiveConsulting/Aeron.NET/pull/43/files

However @omariom pointed out that under the ECMA standard the writes can be re-ordered.

A strategy for protecting against re-ordering volatile writes while keeping most of the performance was to insert a dummy Volatile.Read:
https://github.com/dotnet/coreclr/issues/6121

But there is a bug in the RyuJIT that means that it can be dropped:
https://github.com/dotnet/coreclr/issues/6172

Given that C# compiler doesn't order writes, this isn't a problem for now but I'll leave this here for future reference and we can come back to it once the compiler has been fixed.

**Comment by omariom** [comment]
> But there is a bug in the RyuJIT that means that it can be dropped:
dotnet/coreclr#6172

It drops the read only if the result is put into a local variable.
But you can read into a field.

**Comment by Scooletz** [comment]
@JPWatson Just asking, do you know the definitive answer for this question? Or is it `it depends` ;-)

**Comment by JPWatson** [comment]
I wouldn't say I have a definitive answer. Currently the code only has a volatile write which won't be reordered on x86 but may be on a different architecture/CLR that is more relaxed about write ordering. (https://msdn.microsoft.com/en-us/magazine/jj883956.aspx)
At the point .NET standard supported is added (opening up the range of architectures), I'll have another look at the performance impact of both the original full barrier and the dummy volatile read (assuming the bug in the CLR will be fixed).
Hope this helps :)
