### ISSUE TITLE
Incorrect Aeron driver in Nuget package

### ISSUE THREAD

**Issue by mjpt777** [AdaptiveConsulting/Aeron.NET#54]
https://gitter.im/real-logic/Aeron

> ogreenz @ogreenz 16:02
> Hi, there is some mixup with Aeron.Client which is really a show-stopper. Aeron.Clinet is not truly 1.0.0 as it claims to be. First of all looking at master branch of Aeron.Net at src/Adaptive.Aeron/Properties/AssemblyInfo.cs, it contains [assembly: AssemblyVersion("0.1.0.0")] (changed on July 31st the day of the nuget release). Looking at the dll inside the nuget it says 0.9.9.0, so it's all rather confusing. But the main problem is that in the nuget file the Adaptive.Aeron.dll built withCncFileDescriptor.cs declaring CNC_VERSION = 4 which does not match the media-driver.jar driver version which was bumped as well on July 31st, causing the Aeron.Connect() to fail because of Cnc version incompatibility. Just to make it clear the GitHub version is all good (the driver and the cnc files versions match) it's the nuget that was published that is broken (old source code with new driver), right now I'm working from a side-loaded dll compiled by me but would appreciate the nuget file getting fixed or at least matching it to Aeron.Driver version, thanks!

**Comment by JPWatson** [comment]
@ogreenz Thanks for raising that. The assembly version is fixed and I've published an update to NuGet.
https://www.nuget.org/packages/Aeron.Client/1.0.0.1
Let me know if this works for you.

**Comment by JPWatson** [comment]
v1.0.1 is out now too
