### ISSUE TITLE
Agrona nuget package

### ISSUE THREAD

**Issue by yburke94** [AdaptiveConsulting/Aeron.NET#57]
Would it be possible to package `Agrona` as a separate nuget package. It would be nice to use some of the data structures without pulling in the whole `Aeron.Client` nuget package.

**Comment by JPWatson** [comment]
I've just uploaded a pre-release version of Agrona here as part of the move to support .net standard (#69):
https://www.nuget.org/packages/Agrona/0.9.7-standard

Will transition to stable with the next batch of functionality.

Thanks @UncleFirefox
