### ISSUE TITLE
Crash running in release

### ISSUE THREAD

**Issue by jmazar** [AdaptiveConsulting/Aeron.NET#76]
Hello, I'm using aeron for my .net program and I find that when I build in release mode and offer buffers to a publisher, my program crashes after a little while. 
The error in my log is
```
An unhandled exception of type 'System.AccessViolationException' occurred in Adaptive.Agrona.dll
Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
```
My callstack looks like

```
	Adaptive.Agrona.dll!Adaptive.Agrona.Concurrent.UnsafeBuffer.GetLongVolatile(int index)	Unknown	No symbols loaded.
 	Adaptive.Agrona.dll!Adaptive.Agrona.Concurrent.Broadcast.BroadcastReceiver.ReceiveNext()	Unknown	No symbols loaded.
 	Adaptive.Agrona.dll!Adaptive.Agrona.Concurrent.Broadcast.CopyBroadcastReceiver.Receive(Adaptive.Agrona.Concurrent.MessageHandler handler)	Unknown	No symbols loaded.
 	Adaptive.Aeron.dll!Adaptive.Aeron.ClientConductor.Service(long correlationId, string expectedChannel)	Unknown	No symbols loaded.
 	Adaptive.Aeron.dll!Adaptive.Aeron.ClientConductor.DoWork()	Unknown	No symbols loaded.
 	Adaptive.Agrona.dll!Adaptive.Agrona.Concurrent.AgentRunner.DoDutyCycle(Adaptive.Agrona.Concurrent.IIdleStrategy idleStrategy, Adaptive.Agrona.Concurrent.IAgent agent)	Unknown	No symbols loaded.
 	Adaptive.Agrona.dll!Adaptive.Agrona.Concurrent.AgentRunner.Run()	Unknown	No symbols loaded.
 	System.Threading.Thread.dll!System.Threading.Thread.ThreadMain_ThreadStart()	Unknown	No symbols loaded.
 	System.Private.CoreLib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state)	Unknown	No symbols loaded.
```

And the code that causes the issue is
`let pub = aeron.AddExclusivePublication(config.Channel, config.PubId)`

and in a loop that is called every 4 seconds I execute
```
    let arr = Array.zeroCreate 256
    use buffer = new UnsafeBuffer(arr)
    pub.Offer buffer
```

After 10-15 seconds I get the mentioned error. Am I doing anything obviously wrong?

Thanks,
Jeffrey

**Comment by JPWatson** [comment]
Hey Jeffrey,

Are you keeping a reference to the Aeron client? In the current release version, if falls out of scope and is GCed then the reference to underlying log buffers is released which can cause this error. 
(This is fixed in the next version)

James

**Comment by jmazar** [comment]
James,

You were correct, keeping an explicit reference to the Aeron client resolved my problem. It seemed like F# is more aggressive with GC than C# was in terms of scopes/functions. Do you have any idea when the next version may be released?

Thanks,
Jeffrey

**Comment by JPWatson** [comment]
I'm just porting the latest set of changes that'll bring us up in line with Java's version 1.8.1 and add client support for the Archiver. Source will be available on master in the next couple of days and I'll release to NuGet soon.

**Comment by JPWatson** [comment]
I released 1.8.2 which is in line with the Java version -
https://www.nuget.org/packages/Aeron.Client/1.8.2-pre1

**Comment by jmazar** [comment]
James,

Thanks a lot for the release! I also appreciate you have released it as a .net standard library as well. The project I am working on is cross platform. I will test these fixes this week and get back to you.

**Comment by JPWatson** [comment]
:) Closing this issue for now.
