### ISSUE TITLE
Is Span<T> applicable to Aeron.NET?

### ISSUE THREAD

**Issue by JPWatson** [AdaptiveConsulting/Aeron.NET#77]
https://github.com/dotnet/corefxlab/blob/master/docs/specs/span.md

It seems the obvious place to start incorporating Span would be to add methods on the client facing APIs.
i.e. add a `Publication.Offer(Span<byte>)` and `SpanFragmentHandler.OnHandle(Span<byte> buffer)` + Image/Subscription overloads. 

Open Questions
-----------------
* How to replicate the current buffer operations efficiently with Span? GetLong(offset, Endianess)/PutInt/GetIntVolatile/....
* Where, if anywhere, should we expect to see performance improvements? (working with strings)
* What is the status of Memory<T>?

Help & input is welcome.

**Comment by MatthiasWeiser** [comment]
In general Span/Memory is interesting when doing array operations to avoid allocations when slicing/requiring parts of an array.<br>
From my current understanding Aeron wraps most of this with the UnsafeBuffer - thus I am not so sure if anything more than some additional functions for creating an UnsafeBuffer based on a Span are really required. Accessing the UnsafeBuffer leads to an array which can be transformed to a span directly from the caller.<br>
Memory is essentially required when the heap is involved - e.g. when different threads access the same data and span if it is the stack.<br>
