### ISSUE TITLE
Error when starting Aeron publisher/subscriber via a schedulded tasks using default connect

### ISSUE THREAD

**Issue by MatthiasWeiser** [AdaptiveConsulting/Aeron.NET#79]
When starting Aeron via a schedulded task instead of the console, the following exception is thrown.
<br>
Exception Info: Adaptive.Aeron.Exceptions.DriverTimeoutException
   at Adaptive.Aeron.Aeron+Context.ConnectToDriver()
   at Adaptive.Aeron.Aeron+Context.Conclude()
   at Adaptive.Aeron.Aeron..ctor(Context)
   at Adaptive.Aeron.Aeron.Connect(Context)
   at xxx.AeronPublisher..ctor()
   at xxx.NanexxServerImpl.Run()
   at xxx.Main(System.String[])
<br>
What is missing to connect when using a schedulded task? Maybe I have missed something in the docu....
The aeron connection is build this way;
<code>
            aeron = Aeron.Connect();
            publisher = aeron.AddPublication(channel, streamId);

</code>

**Comment by JPWatson** [comment]
Likely the client and/or driver are being run with a system account.

The default path for communicating between the driver and client is based on the process owner's temp directory.
`%localappdata%\temp\aeron-[username]`

To complicate matters, there's also a difference in the way Java/.NET resolve temp directories for system accounts.

Work out where the driver is putting the cnc file and override the client's path to point to the same place:
```
var ctx = new Aeron.Context()
   .AeronDirectoryName(@"c:\path\to\cnc.dat")

aeron = Aeron.Connect(ctx);
````

Or you can do it the other way round and override the driver's directory by adjusting the `start-media-driver.bat` to:
```
java -Daeron.dir=[path] -cp media-driver.jar io.aeron.driver.MediaDriver
```

Or you do both just to be sure :)

**Comment by MatthiasWeiser** [comment]
Thanks for your quick and thorough response - I have added a reference to the exception in the code documentation.

**Comment by JPWatson** [comment]
:) PR Merged, thanks.
