### ISSUE TITLE
Timeout in newer version?

### ISSUE THREAD

**Issue by jmazar** [AdaptiveConsulting/Aeron.NET#81]
I recently updated from 1.4.0 to 1.9.3 and I have been seeing a bug every now and then where messages will not be sent over ipc. I haven't been able to reproduce this in debug or even reliably in release builds and the only time I've seen it happen is when I've had a connection open for a long period of time (multiple days) without sending any message over aeron. When I would then try to send a message the subscriber would not get any message and I haven't seen any error from the publisher. Then, when I restart the publisher application, the subscriber will receive all the messages I tried to send previously, and have no further problems sending messages.
While I continue to look into this to get more detail, my hunch is that there was some timeout added to connections if messages were not sent over a long period of time. Is this possibly the case? If not I'll try and keep digging.

Thank you,
Jeffrey

**Comment by JPWatson** [comment]
There are no timeouts that have been added that meet that description.
The only timeout that might come into play here is the driver-to-client liveness.

Some avenues for investigation:
* Make sure you're checking the response from Publication.offer
* Use available/unavailable image handlers to log when Images become available or go away.
* Have a look at AeronStat, you can also see counters that represent the subscriber and publication positions and liveness counters for the Aeron clients.
* `java -cp media-driver.jar io.aeron.samples.LogInspector <logFileName>` might be useful to see what's actually been written to the log buffer.

Closing for now, if you manage to narrow it down/reproduce then feel free to re-open.
