### ISSUE TITLE
Update version?

### ISSUE THREAD

**Issue by jmazar** [AdaptiveConsulting/Aeron.NET#93]
Are there any plans to continue updating this project to follow aeron as it is updated?

Cheers,
Jeff

**Comment by JPWatson** [comment]
Yes, absolutely, just a question of finding the time :)

**Comment by jmazar** [comment]
Of course :) Just wondering if this project was dead or dying.

Also I was curious why you didn't build a C++/CLI wrapper for the aeron c++ library?

**Comment by JPWatson** [comment]
Not sure the C++ library existed at the point we started + there are a couple of cluster related components that don't exist.

**Comment by JPWatson** [comment]
I've just pushed 1.21.2 to NuGet.
