### ISSUE TITLE
Port ExpandableArrayBuffer from Agrona

### ISSUE THREAD

**Issue by JPWatson** [AdaptiveConsulting/Aeron.NET#95]
Useful as a scratch buffer when writing messages where size is not known up front.

**Comment by antondelsink** [comment]
Is this still of interest?
Are you willing to add a reference to System.Memory for BinaryPrimitives?

**Comment by JPWatson** [comment]
> Are you willing to add a reference to System.Memory for BinaryPrimitives?

I'd be interested to see what it looks like and see some benchmarks comparing the current implementation.

Could you do a small spike for int/long/double and some benchmarks?

**Comment by antondelsink** [comment]
> benchmarks comparing the current implementation

This is my first look at Aeron, Agrona, and Aeron.NET so I'll leave benchmarking to the performance experts like yourself :)

> Useful as a scratch buffer when writing messages where size is not known up front.

I'm asking if an implementation of ExpandableArrayBuffer would be useful if taking an approach like this:
```
public double GetDouble(int index, ByteOrder byteOrder)
{
    var source = byteArray.AsSpan(index, SIZE_OF_DOUBLE);
    if (NATIVE_BYTE_ORDER == byteOrder)
    {
        return BitConverter.Int64BitsToDouble(BinaryPrimitives.ReadInt64LittleEndian(source));
    }
    else
    {
        return BitConverter.Int64BitsToDouble(BinaryPrimitives.ReadInt64BigEndian(source));
    }
}
```
and/or
```
public void PutLong(int index, long value, ByteOrder byteOrder)
{
    EnsureCapacity(index, SIZE_OF_LONG);

    var target = byteArray.AsSpan(index, SIZE_OF_LONG);

    switch (byteOrder)
    {
        case ByteOrder.BigEndian:
            BinaryPrimitives.WriteInt64BigEndian(target, value);
            break;
        case ByteOrder.LittleEndian:
            BinaryPrimitives.WriteInt64LittleEndian(target, value);
            break;
        }
}
```

**Comment by JPWatson** [comment]
I think we'd need to answer the performance question first before going down that path.

**Comment by MarshalOfficial** [comment]
@JPWatson  Are there any updates on this issue?

**Comment by JPWatson** [comment]
None as of today. I will try to take a look at this while I update to the latest Aeron version.
