### ISSUE TITLE
AtomicCounter can not be used for reading

### ISSUE THREAD

**Issue by szehetner** [AdaptiveConsulting/Aeron.NET#97]
The constructor of AtomicCounter immediately writes 0 into the underlying counter, which makes it impossible to use this class for just reading a counter. 

https://github.com/AdaptiveConsulting/Aeron.NET/blob/fabc0712e73e51688c7dba5b29c5763772c48449/src/Adaptive.Agrona/Concurrent/Status/AtomicCounter.cs#L51 

Notably, the java version doesn't write to the counter: https://github.com/real-logic/agrona/blob/master/agrona/src/main/java/org/agrona/concurrent/status/AtomicCounter.java

Would it be possible to change this or create a constructor overload (or parameter) that doesn't overwrite the value?

**Comment by JPWatson** [comment]
Yes. Will sort it for the next release.
