### ISSUE TITLE
attempting to extend a recording throws exception

### ISSUE THREAD

**Issue by ahychu84** [AdaptiveConsulting/Aeron.NET#98]
Hey Guys,

Just started playing with Aeron using your .NET implementation and I am noticing when I am trying to extend an existing recording I get this coming from the driver. io.aeron.archive.client.ArchiveException: cannot extend recording 0 image joinPosition 0 not equal to recording stopPosition 1536. I have attached a copy of the archiving code that I'm using.

Any advice would be appreciated, thank you so much. On a side note, is there any plans to update this client to work with the most recent build of Aeron?

[program.txt](https://github.com/AdaptiveConsulting/Aeron.NET/files/4670024/program.txt)

**Comment by JPWatson** [comment]
> is there any plans to update this client to work with the most recent build of Aeron
Yes, there is. I plan to do it over the next couple of weeks.

> cannot extend recording 0 image joinPosition 0 not equal to recording stopPosition 1536
You need to apply initialPosition to the channel you create for the publication rather than the channel for extendRecording.

**Comment by ahychu84** [comment]
> > is there any plans to update this client to work with the most recent build of Aeron
> 
> Yes, there is. I plan to do it over the next couple of weeks.
> 

Are you planning to update to 1.28? I noticed it got pushed and from what i've been reading is feature full for Aeron cluster.

**Comment by JPWatson** [comment]
> Are you planning to update to 1.28?

👍

**Comment by ahychu84** [comment]
> > Are you planning to update to 1.28?
> 
> 👍

Perfect! Thank you so much. Is there anything that I might be able to help with ?

**Comment by JPWatson** [comment]
> Are you planning to update to 1.28? 

1.28.2 has been released.
